# Generated by Django 4.2.4 on 2023-10-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255)),
                ('start_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('landing_date', models.CharField(max_length=255)),
                ('flying_date', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('airplane_company', models.CharField(max_length=255)),
            ],
        ),
    ]
